[package]
name = "mocking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
mockall = "0.12.1"
mockall_double = "0.3.1"
tokio = { version = "1.32", features = ["full"] }
